#
# embeddinggemma
#
embedding-model.name=embeddinggemma
embedding-model.folder=embeddinggemma-300m
embedding-model.url=https://huggingface.co/google/embeddinggemma-300m
embedding-model.license=gemma
embedding-model.runtime_engine=OnnxRuntime
embedding-model.device=cpu
#
embedding-model.optMLArg.padding=true
embedding-model.optMLArg.truncation=true
embedding-model.optMLArg.pooling=mean
embedding-model.optMLArg.includeTokenTypes=false
#####################################