#
# all-MiniLM
#
embedding-model.name=all-MiniLM
embedding-model.folder=all-MiniLM-L12-v2
embedding-model.url=https://huggingface.co/sentence-transformers/all-MiniLM-L12-v2
embedding-model.license=Apache-2.0
embedding-model.runtime_engine=OnnxRuntime
embedding-model.device=cpu
#
embedding-model.optMLArg.padding=true
embedding-model.optMLArg.truncation=true
embedding-model.optMLArg.includeTokenTypes=true
######################