#
# granite-embedding
#
embedding-model.name=granite-embedding
embedding-model.english.folder=granite-embedding-english-r2
embedding-model.multilingual.folder=granite-embedding-97m-multilingual-r2
#
embedding-model.runtime_engine=OnnxRuntime
embedding-model.device=cpu
#
embedding-model.optMLArg.padding=true
embedding-model.optMLArg.truncation=true
embedding-model.optMLArg.pooling=mean
embedding-model.optMLArg.includeTokenTypes=false
######################################